version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
    networks:
       - overlay
    container_name: stock-db
  web:
    restart: always
    build: .
    command: bash -c "python manage.py makemigrations &&python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
       - overlay
    container_name: stock
  selenium:
      build:
        context: .
        dockerfile: ./DockerfileSmartLab
      ports:
        - "4000:4000"
      networks:
       - overlay
      volumes:
        - .:/usr/src/app
      container_name: stock-selen
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      privileged: true
  rabbitmq:
    restart: always
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
     - overlay
    volumes:
        - ./myrabbit.conf:/etc/rabbitmq/rabbitmq.conf
  celery:
    build: .
    container_name: 'stock-tasks'
    command: bash -c "celery -A stockex worker -l INFO --concurrency=8"
    ports:
      - 5555:5555
    volumes:
      - .:/code
    restart: always
    environment:
      - TZ=Europe/Moscow
    links:
      - rabbitmq
      - web
    networks:
     - overlay
  celery_beat:
    build: .
    command: celery -A celery_beat beat --loglevel=INFO
    volumes:
      - .:/code
    networks:
     - overlay
networks:
  overlay:
