version: '3'

services:
  selenium:
    image: selenium/standalone-firefox
    ports:
    - 4444:4444
    restart: always

  app:
    build:
      context: .
    volumes:
    - ./StockExcanger:/StockExcanger
    command: sh -c "python3 7.py"
    depends_on:
    - selenium
