# Generated by Django 3.2.10 on 2021-12-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('price', models.IntegerField(null=True)),
                ('pe', models.IntegerField(null=True)),
                ('ps', models.IntegerField(null=True)),
                ('pb', models.IntegerField(null=True)),
                ('ebitda', models.IntegerField(null=True)),
                ('env', models.IntegerField(null=True)),
                ('net_worth', models.IntegerField(null=True)),
                ('roe', models.IntegerField(null=True)),
                ('debt_eq', models.IntegerField(null=True)),
                ('roa', models.IntegerField(null=True)),
                ('roi', models.IntegerField(null=True)),
                ('last_divident', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.IntegerField(null=True)),
                ('gross_profit', models.IntegerField(null=True)),
                ('income_after_taxes', models.IntegerField(null=True)),
                ('net_income', models.IntegerField(null=True)),
                ('debt', models.IntegerField(null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockouter.stock')),
            ],
        ),
    ]
